
# Generated by Django 4.2.5 on 2023-09-14 06:37


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0003_remove_post_pub_date_post_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.CharField(default="전체", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
