# Generated by Django 4.2.5 on 2023-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0004_post_author_post_topic_post_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information", models.CharField(max_length=200)),
            ],
        ),
    ]
